# 是否开启jmcomic的日志输出
log: false

# 配置客户端相关
client:
  # 使用网页端，效率更高
  impl: html
  # 配置多个域名，按顺序尝试
  domain:
    - 18comic.vip
    - 18comic.org
    - jm-comic.org
    - jm-comic2.cc
  # 请求失败重试次数
  retry_times: 5
  # 请求配置
  postman:
    meta_data:
      # 使用系统代理，默认clash端口
      proxies: 
        http: http://127.0.0.1:7890
        https: http://127.0.0.1:7890
      # 如果需要登录，在这里配置cookies
      cookies: null

# 下载配置
download:
  # 启用缓存，避免重复下载
  cache: true
  # 图片配置
  image:
    # 还原混淆的图片
    decode: true
    # 统一转换为jpg格式
    suffix: .jpg
  # 并发配置
  threading:
    # 同时下载30张图片
    image: 30
    # 同时下载的章节数，默认使用CPU线程数
    photo: 16

# 文件夹规则配置
dir_rule:
  # 下载根目录，使用相对路径
  base_dir: "./downloads"
  # 使用默认规则：根目录/章节标题/图片文件
  rule: Bd_Ptitle